version: "3.3"
services:
  db:
    image: mysqldb
    build: ./docker/mysqldb
    container_name: mysql1
    ports:
        - "53306:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: repo
        MYSQL_DATABASE: repodb
        MYSQL_USER: repo
        MYSQL_PASSWORD: repo
  redis:
    image: tutum/redis
    hostname: "redis"
    environment:
      - REDIS_PASS=**None**
    container_name: redis1
    ports:
      - "6379:6379"
  rabbitmq:
    image: "bitnami/rabbitmq"
    container_name: rabbitmq1
    environment:
      RABBITMQ_ERL_COOKIE: "ABQOKOFSQALCPCLNLEQG"
      RABBITMQ_USERNAME: "admin"
      RABBITMQ_PASSWORD: "repormq"
      RABBITMQ_VHOST: "/"
      RABBITMQ_DISK_FREE_LIMIT: "{mem_relative, 0.1}"
    ports:
      - "55673:15672"
      - "5672:5672"
    expose:
      - 5672
      - 15672
    healthcheck:
      test: [ "CMD", "nc", "-z", "localhost", "5672" ]
      interval: 5s
      timeout: 15s
      retries: 1
    labels:
      NAME: "rabbitmq"
  solr:
    image: solris:latest
    build: ./docker/solris
    hostname: "solr"
    container_name: solris1
    ports:
      - "8983:8983"
  earkweb:
    image: earkweb:latest
    build: .
    container_name: earkweb1
    command: /earkweb/run_earkweb.sh
    #user: ${USER}:${USER}
    ports:
      - "8000:8000"
    volumes:
      - "/d1/sample/repo:/var/data/repo"
    links:
      - flower
      - db
      - redis
      - rabbitmq
      - solr
    depends_on:
      - redis
      - rabbitmq
      - db
      - celery
  celery:
    image: earkweb:latest
    build: .
    container_name: celery1
    command: /earkweb/run_celery.sh
    #user: ${USER}:${USER}
    volumes:
      - "/d1/sample/repo:/var/data/repo"
    restart: on-failure
    links:
      - redis
      - rabbitmq
    depends_on:
      - redis
      - rabbitmq
  flower:
    image: earkweb:latest
    build: .
    container_name: flower1
    command: /earkweb/run_flower.sh
    ports:
      - "5555:5555"
    links:
      - redis
      - rabbitmq
    depends_on:
      - redis
      - celery
