version: '2'
services:
  db:
    image: earkdbimg
    container_name: earkdb_1
    build: ./docker/earkdb
    volumes:
      - /tmp/earkweb-mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
  solr:
    image: solr
    container_name: solr_1
    ports:
      - '8983:8983'
  rabbitmq:
    image: tutum/rabbitmq
    environment:
      - RABBITMQ_PASS=mypass
    container_name: rabbitmq_1
    ports:
      - "5672:5672"
      - "15672:15672"
    links:
      - db
  earkweb:
    image: earkwebimg
    build: .
    container_name: earkweb_1
    command: /earkweb/run_web.sh
    volumes:
      - .:/earkweb
      - /tmp/earkwebdata:/var/data/earkweb
    ports:
      - "8000:8000"
    links:
      - db
      - solr
      - celery
      - rabbitmq
  celery:
    build: .
    container_name: celery_1
    command: /earkweb/run_celery.sh
    environment:
      - C_FORCE_ROOT=1
    volumes:
      - .:/earkweb
      - /tmp/earkwebdata:/var/data/earkweb
    links:
      - rabbitmq
      - db
