version: '2'
services:
  db:
    volumes:
      - /var/data/docker-mysql:/var/lib/mysql
    image: tutum/mysql 
    ports:
      - '127.0.0.1:3306:3306'
  web:
    image: earkweb
    command: python /earkweb/manage.py runserver 0.0.0.0:8000
    volumes:
      - /var/data/docker-earkweb:/var/data/earkweb
    ports:
      - "8000:8000"
    depends_on:
      - db
