version: "2.1"
services:
  db:
    image: mysqldb
    build: ./docker/mysqldb
    container_name: mysql1
    ports:
        - "53306:3306"
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: eark
        MYSQL_DATABASE: earkdb
        MYSQL_USER: eark
        MYSQL_PASSWORD: eark
  redis:
    image: tutum/redis
    hostname: "redis"
    environment:
      - REDIS_PASS=**None**
    container_name: redis1
    ports:
      - "56379:6379"
  rabbitmq:
    image: "bitnami/rabbitmq"
    container_name: rabbitmq1
    environment:
      RABBITMQ_ERL_COOKIE: "ABQOKOFSQALCPCLNLEQG"
      RABBITMQ_USERNAME: "admin"
      RABBITMQ_PASSWORD: "earkrmq"
      RABBITMQ_VHOST: "/"
    ports:
      - "55673:15672"
      - "55672:5672"
    labels:
      NAME: "rabbitmq"
  solr:
    image: solris:latest
    build: ./docker/solris
    hostname: "solr"
    container_name: solris1
    ports:
      - "8983:8983"
  earkweb:
    image: earkweb:latest
    build: .
    container_name: earkweb1
    command: /earkweb/run_all.sh
    ports:
      - "8000:8000"
      - "5555:5555"
    links:
      - db
      - redis
      - rabbitmq
      - solr
networks:
  backend:
    external: true
